spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: nicat
    hikari:
      schema: nijat_bank
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    hibernate:
#      ddl-auto: create
